find_package(Qt5 REQUIRED COMPONENTS Core)
find_package(Threads REQUIRED)
if(BUILD_TESTING)
    add_executable(background-task-test tests/test.cpp)
    target_link_libraries(background-task-test PRIVATE Qt5::Core Threads::Threads)
    target_compile_features(background-task-test PRIVATE cxx_std_17)
    foreach(MODE quit exit scope)
        add_test(NAME background-task-${MODE} COMMAND background-task-test ${MODE})
        set_tests_properties(background-task-${MODE} PROPERTIES TIMEOUT 10)
    endforeach()
endif()
